---
driver:
  name: docker
platforms:
  - name: symplegma-containerd-test
    image: geerlingguy/docker-ubuntu2404-ansible:latest@sha256:18bf80157ea24b3210eb25ca89a5460912271b0ee61f238f36d2b115c89e39e6
    command: /lib/systemd/systemd
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      inject_facts_as_vars: false
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - syntax
    - create
    - converge
    - verify
    - destroy
